### ISSUE TITLE
about data

### ISSUE THREAD

**Issue by wwrong01** [stegmuel/ScoreNet#2]
Hi,could you please release the  data directory structure cause i don't really know  about  the source and target data,thanks!I really like your paper!

**Comment by stegmuel** [comment]
Hi,
I updated the repo to depict the data directory structure. 
"Source" refers to the image from which content is cut and "target" to the one where the content is pasted. Please check the latest version of the paper (link in the README), as we changed the potentially confusing "source/target" terminology.

**Comment by wwrong01** [comment]
Hi,
&nbsp; &nbsp; Thanks a lot for your replies very much, I think i forgot the content of your article since i read it last year,&nbsp; so i read it again and understood that problem.Now i'm learning your code and will visit your homepage angin.Your article&nbsp; is very creative,thanks you for exposing!
&nbsp;


王伟蓉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月7日(星期二) 下午5:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [stegmuel/ScoreNet] about data (Issue #2)





 
Hi,
 I updated the repo to depict the data directory structure.
 "Source" refers to the image from which content is cut and "target" to the one where the content is pasted. Please check the latest version of the paper (link in the README), as we changed the potentially confusing "source/target" terminology.

**Comment by stegmuel** [comment]
You are welcome and thanks for the feedback.

**Comment by wwrong01** [comment]
Hi,
&nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; I tried to replicate your results with the same dataset as yours，but it's not achieved desired results as yours , i try to use the pre-trained method and your code with the environment as you mentioned in your github page .So,can you tell me some details that i may had ignored? I really need your help ,thanks a lot,love you!



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 7, 2023 17:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [stegmuel/ScoreNet] about data (Issue #2)




 
Hi,
 I updated the repo to depict the data directory structure.
 "Source" refers to the image from which content is cut and "target" to the one where the content is pasted. Please check the latest version of the paper (link in the README), as we changed the potentially confusing "source/target" terminology.

**Comment by stegmuel** [comment]
Hi,

Here are a few things that you may want to check:
1) Do you use the same version of the dataset as we do? We used the "previous" version of the dataset to be able to compare our implementation to existing baselines. To get this version we had to reach out to one of the authors of BRACS.
2) What kind of pre-training are you using? We used DINO for the scorer and the high-resolution stage. You should probably check the quality of your pre-trained scorer with a linear evaluation on a downscale version of BRACS for instance.  My guess is that even a ViT-S/16 pre-trained on ImageNet would already do the job.
3) If training is unstable you might want to freeze the first layers of your scorer.

I hope this helps.

**Comment by WunnH** [comment]
> 
Hello, I would like to ask, when I use the pre-trained weights of VIT_B_16, I encounter the following error: RuntimeError: Error(s) in loading state_dict for ScoreNet. Does this indicate that this model is not compatible with pre-trained weights from VIT imageNet1k?
