### ISSUE TITLE
Pre-training weight

### ISSUE THREAD

**Issue by WunnH** [stegmuel/ScoreNet#3]
Hello, thank you very much for your excellent work. Could you please share the weight of your pre-training BRACS

**Comment by stegmuel** [comment]
Hello,
I'll try to provide the weights of the model pre-trained on BRACS. It requires a bit of work as I refactored the code of the ScoreNet model and the keys of the state_dict will not match.

**Comment by WunnH** [comment]
Thank you very much. One pre-trained weight is crucial for me because I currently lack the resources to obtain a pre-trained weight myself. If it could be provided as soon as possible, I would be extremely grateful.

**Comment by SheerazGul** [comment]
hey @wangxinghangcnn, I have run your code on the BRACS dataset and the final f1 score I am getting is 1.30e-01. could you please explain how can I fine tune the model to achieve the best f1. If you could provide per-training weights that would be great.

**Comment by stegmuel** [comment]
Hi,
It is expected that training ScoreNet from scratch on a small dataset would not work well. In the paper, we first pre-train the scorer and the aggregation's stage ViTs using DINO (https://github.com/facebookresearch/dino). In the case of BRACS, it is easy to obtain decent-sized unlabeled datasets as they also provide the WSIs from which the TRoIs were extracted. In Table 13 (https://arxiv.org/pdf/2202.07570.pdf) we report an F1-score of 55.5 when training a linear layer on top of the frozen weights obtained from the pre-training of the scorer's ViT and using a downscaled version of BRACS (s=8). In hindsight, I would argue that using publicly available pre-trained models, e.g., a  ViT-S/16 pre-trained on ImageNet with DINO for both the scorer and the aggregation's stage models would yield improved scores and mitigate the need for the SSL pre-training. It should be straightforward to modify the code such that it loads pre-trained ViT-S/16 for the scorer and the aggregation stage.

**Comment by SheerazGul** [comment]
> Hi, It is expected that training ScoreNet from scratch on a small dataset would not work well. In the paper, we first pre-train the scorer and the aggregation's stage ViTs using DINO (https://github.com/facebookresearch/dino). In the case of BRACS, it is easy to obtain decent-sized unlabeled datasets as they also provide the WSIs from which the TRoIs were extracted. In Table 13 (https://arxiv.org/pdf/2202.07570.pdf) we report an F1-score of 55.5 when training a linear layer on top of the frozen weights obtained from the pre-training of the scorer's ViT and using a downscaled version of BRACS (s=8). In hindsight, I would argue that using publicly available pre-trained models, e.g., a ViT-S/16 pre-trained on ImageNet with DINO for both the scorer and the aggregation's stage models would yield improved scores and mitigate the need for the SSL pre-training. It should be straightforward to modify the code such that it loads pre-trained ViT-S/16 for the scorer and the aggregation stage.

i followed this process still the highest f1 i am getting is around 47. i first pre-trained the vit small 16 and the trained it with scorenet with your code. both on the downscaled version of BRACS
