### ISSUE TITLE
Problem about dataset

### ISSUE THREAD

**Issue by syguo95** [stegmuel/ScoreNet#4]
Hi,
I noticed that BACH dataset had been used in this research. 
On the official BACH website, only training label are given and the 100 test images have no labels. So I just wonder if there is a way I could obtain the labels of BACH test dataset ?

**Comment by stegmuel** [comment]
Hi,
Yes this is correct we used the BACH dataset, but only for the purpose of a transfer learning evaluation. In that setting the training samples were sufficient. We were not able to access the test labels either.
